POST http://localhost:3000/comments/recipe/62b1dd9e0e3c776ee34a3800 HTTP/1.1
content-type: application/json

{
    "comment": "This is cool"
}

###
GET http://localhost:3000/comments/recipe/62b1dd9e0e3c776re34a3800 HTTP/1.1

###
GET http://localhost:3000/comments/user/ HTTP/1.1

# NOT READY

###
PUT http://localhost:3000/comments/62b9c8257a9e43dbc90cbe7d HTTP/1.1
content-type: application/json

{
    "comment": "this recipe is alright :/"
}

###
DELETE http://localhost:3000/comments/62b9c8257a9e43dbc90cbe7d HTTP/1.1